export const CAMPAIGN_ACTION_TYPES = {
  //   FETCH_CAMPAIGNS_START: "campaign/FETCH_CAMPAIGNS_START",
  //   FETCH_CAMPAIGNS_SUCCESS: "campaign/FETCH_CAMPAIGNS_SUCCESS",
  //   FETCH_CAMPAIGNS_FAILED: "campaign/FETCH_CAMPAIGNS_FAILED",
};
